name: call_monitor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  call_log: ^6.0.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  flutter_contacts: ^1.1.7+1
  drift: ^2.16.0
  sqlite3_flutter_libs: ^0.5.21
  path_provider: ^2.1.1
  path: ^1.9.0
  flutter_heatmap_calendar: ^1.0.5
  timeline_tile: ^2.0.0
  intl: ^0.19.0
  svg_flutter: ^0.0.1
  workmanager: ^0.9.0
  flutter_local_notifications: ^17.0.0
  url_launcher: ^6.2.3
  google_fonts: ^8.0.0
  permission_handler: ^12.0.1
  timezone: ^0.9.4
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  drift_dev: ^2.16.0
  flutter_gen_runner: ^5.6.0
  build_runner: ^2.4.13
  dart_style: ^3.0.1
  build: ^2.4.1
  build_config: ^1.1.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
